name: Build and Push Docker to GCP Artifact Registry

on:
  push:
    branches:
      - infra
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Determine Docker Tag
        id: docker_tag
        run: |
          if [ "${GITHUB_REF##*/}" = "infra" ]; then
            echo "TAG=latest" >> $GITHUB_ENV
          elif [ "${GITHUB_REF##*/}" = "main" ]; then
            echo "TAG=stable" >> $GITHUB_ENV
          else
            echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV
          fi

      - name: Build Docker image
        run: |
          docker build -t web-app .

      - name: Tag Docker image for Artifact Registry
        run: |
          docker tag web-app us-central1-docker.pkg.dev/glass-ally-479415-q8/docker-repo/web-app:${{ env.TAG }}

      - name: Push Docker image to Artifact Registry
        run: |
          docker push us-central1-docker.pkg.dev/glass-ally-479415-q8/docker-repo/web-app:${{ env.TAG }}

      - name: Show pushed image
        run: |
          echo "Pushed image: us-central1-docker.pkg.dev/glass-ally-479415-q8/docker-repo/web-app:${{ env.TAG }}"
